// LOS SERVICIOS SE USAN PARA HACER LLAMADAS A APLICACIONES/SERVIDORES EXTERNAS (BBDD; API; ETC)
// ESTE SERVICIO LLAMA A LA API DE RICK Y MORTY

//? FUNCION QUE LLAMA A LA URL CON TODOS LOS PERSONAJES --> https://rickandmortyapi.com/api/character
//? FUNCION QUE LLAMA A LA URL QUE TIENE EL FILTRO A PERSONAJES POR NOMBRE --> https://rickandmortyapi.com/api/character/?name=NOMBRE